version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - PAYLOAD_SECRET=${PAYLOAD_SECRET}
    ports:
      - '3000:3000'
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NODE_ENV=production
