/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    Outgoings: Outgoing;
    PortfolioItems: PortfolioItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    Outgoings: OutgoingsSelect<false> | OutgoingsSelect<true>;
    PortfolioItems: PortfolioItemsSelect<false> | PortfolioItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'editor' | 'user';
  status: 'active' | 'suspended';
  phone?: string | null;
  addresses?:
    | {
        /**
         * e.g. Home, Work
         */
        label?: string | null;
        type: 'shipping' | 'billing' | 'both';
        line1: string;
        line2?: string | null;
        city: string;
        state?: string | null;
        postalCode: string;
        country: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes about this user
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  name?: string | null;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Outgoings".
 */
export interface Outgoing {
  id: number;
  name: string;
  amount: number;
  frequency: 'weekly' | 'monthly' | 'yearly';
  startDate: string;
  /**
   * Examples: Software, Rent, Contractors, Marketing.
   */
  category?: string | null;
  adminNotes?: string | null;
  status: 'active' | 'paused' | 'ended';
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioItems".
 */
export interface PortfolioItem {
  id: number;
  title: string;
  /**
   * A short public summary used on cards and listing pages.
   */
  shortDescription?: string | null;
  /**
   * Public-facing overview for the portfolio detail page.
   */
  overview?: string | null;
  /**
   * Internal scope, notes, and delivery details.
   */
  projectDetails?: string | null;
  challenge?: string | null;
  solution?: string | null;
  outcome?: string | null;
  /**
   * Optional client or project logo.
   */
  logo?: (number | null) | Media;
  /**
   * Optional external logo URL.
   */
  logoUrl?: string | null;
  /**
   * Portfolio card/detail background image or video.
   */
  backgroundMedia?: (number | null) | Media;
  /**
   * Alt text for the background media when it is an image.
   */
  backgroundMediaAlt?: string | null;
  /**
   * Use dark text when the portfolio card background is white or very light.
   */
  cardTextTone?: ('light' | 'dark') | null;
  /**
   * Transparent foreground image or video layered over the card background.
   */
  foregroundMedia?: (number | null) | Media;
  /**
   * Alt text for the foreground media when it is an image.
   */
  foregroundMediaAlt?: string | null;
  featuredImage?: (number | null) | Media;
  featuredImageAlt?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  clientCompany?: string | null;
  /**
   * Public website URL for the portfolio item.
   */
  websiteUrl?: string | null;
  ownerName?: string | null;
  ownerEmail?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  /**
   * Industry or market this work belongs to.
   */
  industry?: string | null;
  /**
   * e.g. "Nelson, NZ"
   */
  location?: string | null;
  /**
   * e.g. Website, branding, renovation, installation.
   */
  projectType?: string | null;
  completionDate?: string | null;
  /**
   * Services delivered for this item.
   */
  services?:
    | {
        service?: string | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  constraints?:
    | {
        constraint?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Track each job, project, product, or service delivered for this client.
   */
  jobs?:
    | {
        category?: string | null;
        jobName?: string | null;
        description?: string | null;
        price?: number | null;
        monthlyFee?: number | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional team list for this portfolio item.
   */
  teamMembers?:
    | {
        name?: string | null;
        role?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional testimonial.
   */
  testimonial?: {
    name?: string | null;
    message?: string | null;
    rating?: number | null;
    image?: (number | null) | Media;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (number | null) | Media;
  };
  /**
   * Automatic if left blank
   */
  slug: string;
  clientStatus?: ('lead' | 'active' | 'paused' | 'complete' | 'archived') | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  featured?: boolean | null;
  isFeaturedOnHomepage?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'Outgoings';
        value: number | Outgoing;
      } | null)
    | ({
        relationTo: 'PortfolioItems';
        value: number | PortfolioItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  status?: T;
  phone?: T;
  addresses?:
    | T
    | {
        label?: T;
        type?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  name?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Outgoings_select".
 */
export interface OutgoingsSelect<T extends boolean = true> {
  name?: T;
  amount?: T;
  frequency?: T;
  startDate?: T;
  category?: T;
  adminNotes?: T;
  status?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioItems_select".
 */
export interface PortfolioItemsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  overview?: T;
  projectDetails?: T;
  challenge?: T;
  solution?: T;
  outcome?: T;
  logo?: T;
  logoUrl?: T;
  backgroundMedia?: T;
  backgroundMediaAlt?: T;
  cardTextTone?: T;
  foregroundMedia?: T;
  foregroundMediaAlt?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  clientCompany?: T;
  websiteUrl?: T;
  ownerName?: T;
  ownerEmail?: T;
  contactName?: T;
  contactEmail?: T;
  industry?: T;
  location?: T;
  projectType?: T;
  completionDate?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  constraints?:
    | T
    | {
        constraint?: T;
        id?: T;
      };
  jobs?:
    | T
    | {
        category?: T;
        jobName?: T;
        description?: T;
        price?: T;
        monthlyFee?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  teamMembers?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        name?: T;
        message?: T;
        rating?: T;
        image?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
      };
  slug?: T;
  clientStatus?: T;
  status?: T;
  publishedAt?: T;
  featured?: T;
  isFeaturedOnHomepage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}